---
version: 2
jobs:
  build:
    macos:
      xcode: "11.2.1"
    steps:
      - checkout
      - run: brew update
      - run: brew install shellcheck
      - run: shellcheck install 
      - run: ./install
